#!/bin/bash -e

chown www-data /srv/www

sudo -E -u www-data /scripts/build.sh >> /dev/null

/scripts/generate-config.sh /etc/nginx/sites-enabled/default 2>&1

service nginx reload >> /dev/null

exec sleep infinity
